import {money,seafood,effectivePrice,analyze,normalizeHistory,latestSnapshots,COURSES,course,deal} from './lib/prices.mjs';
import {receiptPoints,purchases} from './lib/receipts.mjs';
import {tokens,dishIndex,dishGroups,matchKind} from './lib/dishes.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let history=[],latest=[],rows=[],receipts=null,groups=[],dishes=[],limit=24;const fmt=s=>new Date(s).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const TABS=[['mina','Mina rätter'],...COURSES],tab=()=>{const h=location.hash.slice(1);return TABS.some(([k])=>k===h)?h:groups.length?'mina':'mat';};
const belowUsual=r=>r.bought&&r.price<r.bought.usual?r.bought.usual-r.price:0;
const under=(d,r)=>d.g.members.get(r.item)==='variant'?0:Math.max(0,d.g.usual-r.price),dishOffer=d=>d.best&&(d.best.deal.level||under(d,d.best));
function dishCard(d,i){const g=d.g,b=d.best,bought=`<div class="bought"><span>Köpt ${g.times} gånger</span> · du brukar betala ${money(g.usual)}</div>`;
 if(!b)return `<article class="card dish off"><h3>${esc(g.title)}</h3>${bought}<p class="description">Finns inte på någon bevakad meny just nu. Rätter från nya restauranger dyker upp efter nästa insamling.</p></article>`;
 const below=under(d,b),sale=b.price<b.item.originalPrice,venues=new Set(d.m.map(r=>r.s.url)).size;
 const tag=b.deal.level?`<span class="tag t${b.deal.level}">${esc(b.deal.label)}</span>`:below>0?'<span class="tag t1">Under ditt vanliga pris</span>':'',save=below>0?`<span class="save">${money(below)} under ditt vanliga</span>`:b.deal.save>0?`<span class="save">Spara ${money(b.deal.save)}</span>`:'';
 return `<article class="card dish${b.deal.level?' lvl'+b.deal.level:''}"><div class="card-top">${tag}${save}</div><h3>${esc(g.title)}</h3>${bought}<div class="best">Billigast just nu</div><div class="price-row"><span class="price">${money(b.price)}</span>${sale?`<del>${money(b.item.originalPrice)}</del>`:''}</div><div class="venue">${esc(b.s.name)}<span> · ${esc(b.item.name)}${g.members.get(b.item)==='variant'?' (annan variant)':''}</span></div>${b.item.woltPlus&&$('#plus').checked?'<div class="membership">Priset kräver Wolt+</div>':''}<div class="card-bottom"><button class="compare" data-dish="${i}">${d.m.length>1?`Jämför ${d.m.length} alternativ hos ${venues} ${venues===1?'restaurang':'restauranger'} →`:'Visa detaljer →'}</button><a class="order" href="${esc(b.s.url)}" target="_blank" rel="noopener noreferrer">Wolt ↗</a></div></article>`;}
function showDish(d){$('#dishTitle').textContent=d.g.title;$('#dishSub').textContent=`Köpt ${d.g.times} gånger hos ${d.g.venues.join(', ')} · du brukar betala ${money(d.g.usual)}`;
 $('#dishList').innerHTML=d.m.map(r=>{const idx=rows.indexOf(r),sale=r.price<r.item.originalPrice,below=under(d,r),kind=d.g.members.get(r.item);return `<li class="opt${r===d.best?' first':''}"><div class="opt-main"><b>${esc(r.s.name)}</b><span>${esc(r.item.name)}${kind==='variant'?' · annan variant eller storlek':kind==='similar'?' · liknande rätt':''}</span><div>${r.deal.level?`<span class="tag t${r.deal.level}">${esc(r.deal.label)}</span> `:''}${below>0?`<small class="under">${money(below)} under ditt vanliga</small>`:''}${r.item.woltPlus&&$('#plus').checked?'<small> Kräver Wolt+</small>':''}</div></div><div class="opt-price"><span>${money(r.price)}</span>${sale?`<del>${money(r.item.originalPrice)}</del>`:''}</div><div class="opt-links"><button class="history-button" data-index="${idx}">Prishistorik</button><a class="order" href="${esc(r.s.url)}" target="_blank" rel="noopener noreferrer">Wolt ↗</a></div></li>`;}).join('');
 $('#dishList').querySelectorAll('[data-index]').forEach(b=>b.addEventListener('click',()=>{$('#dishDialog').close();showHistory(rows[Number(b.dataset.index)]);}));$('#dishDialog').showModal();}
function card(r){const idx=rows.indexOf(r),sale=r.price<r.item.originalPrice,st=r.stats,d=r.deal;
 const change=st.change?`${st.change<0?'↓':'↑'} ${money(Math.abs(st.change))} sedan förra avläsningen`:'';
 const tag=d.level?`<span class="tag t${d.level}">${esc(d.label)}</span>`:'',save=d.save>0?`<span class="save">Spara ${money(d.save)}</span>`:'';
 const usual=st.median&&d.level===3?`<div class="usual">Brukar kosta ${money(st.median)}</div>`:'',b=r.bought,mine=belowUsual(r);
 const bought=b?`<div class="bought"><span>Köpt ${b.times} ${b.times===1?'gång':'gånger'}</span> · ${b.times===1?'du betalade':'du brukar betala'} ${money(b.usual)}${mine?` <b>· ${money(mine)} billigare nu</b>`:''}</div>`:'';
 return `<article class="card${d.level?' lvl'+d.level:''}"><div class="card-top">${tag}${save}</div><h3>${esc(r.item.name)}</h3><div class="venue">${esc(r.s.name)}<span> · ${esc(r.item.category||'Meny')}</span></div><p class="description">${esc(r.item.description)}</p><div class="price-row"><span class="price">${money(r.price)}</span>${sale?`<del>${money(r.item.originalPrice)}</del>`:''}</div>${usual}${bought}${r.item.woltPlus&&$('#plus').checked?'<div class="membership">Priset kräver Wolt+</div>':''}${change?`<div class="change${st.change<0?' down':''}">${esc(change)}</div>`:''}<div class="card-bottom"><button class="history-button" data-index="${idx}">↗ Prishistorik</button><a class="order" href="${esc(r.s.url)}" target="_blank" rel="noopener noreferrer">Visa på Wolt ↗</a></div></article>`;}
function render(){
 const plus=$('#plus').checked,q=$('#search').value.toLocaleLowerCase('sv'),restaurant=$('#restaurant').value,budget=Number($('#budget').value),current=tab();
 rows=latest.flatMap(s=>s.items.filter(i=>i.available).map(item=>{const price=effectivePrice(item,plus),stats=item.stats[plus];return {s,item,price,stats,course:item.course,bought:item.bought,deal:deal(item,price,stats)};}));
 const seen=new Set();rows=rows.sort((a,b)=>a.item.id.localeCompare(b.item.id)).filter(r=>{const key=JSON.stringify([r.s.url,r.item.name,r.item.description,r.price,r.item.originalPrice,r.item.woltPlus]);if(seen.has(key))return false;seen.add(key);return true;});
 const offer=r=>r.deal.level||belowUsual(r),common=r=>(!restaurant||r.s.url===restaurant)&&(!q||(r.item.name+' '+r.item.description+' '+r.s.name).toLocaleLowerCase('sv').includes(q))&&(!$('#onlyDeals').checked||offer(r));
 const base=rows.filter(r=>common(r)&&r.price<budget&&(!$('#noFish').checked||!seafood(r.item))),inTab=k=>k==='mina'?dishes:base.filter(r=>r.course===k);
 dishes=groups.map(g=>{const m=rows.filter(r=>g.members.has(r.item)&&(!restaurant||r.s.url===restaurant)).sort((a,b)=>a.price-b.price);return {g,m,best:m[0]};}).filter(d=>(!q||(d.g.title+' '+d.m.map(r=>r.item.name+' '+r.s.name).join(' ')).toLocaleLowerCase('sv').includes(q))&&(!$('#onlyDeals').checked||dishOffer(d))&&(!restaurant||d.best));
 $('#tabs').innerHTML=TABS.map(([k,label])=>{const list=inTab(k),deals=list.filter(k==='mina'?dishOffer:r=>r.deal.level).length;return `<a href="#${k}" class="tab${k===current?' active':''}${k==='mina'?' mine':''}"${k===current?' aria-current="page"':''}><span>${label}</span><small>${list.length} rätter${deals?` · <b>${deals} ${deals===1?'erbjudande':'erbjudanden'}</b>`:''}</small></a>`;}).join('');
 const mode=$('#sort').value,isMine=current==='mina';$('#mineNote').hidden=!isMine;
 if(isMine){const ds=[...dishes].sort((a,b)=>Number(!!b.best)-Number(!!a.best)||Number(!!dishOffer(b))-Number(!!dishOffer(a))||(b.best?.deal.level??0)-(a.best?.deal.level??0)||(b.best?under(b,b.best):0)-(a.best?under(a,a.best):0)||b.g.times-a.g.times);
  const n=ds.filter(dishOffer).length,sec=(t,l,note)=>l.length?`<h2 class="group">${t} <span>${note}</span></h2><div class="grid">${l.map(d=>dishCard(d,ds.indexOf(d))).join('')}</div>`:'';
  $('#cards').innerHTML=(sec('Bästa erbjudandena just nu',ds.slice(0,n),n+' st')+sec(n?'Dina övriga favoriter':'Dina favoriter',ds.slice(n),(ds.length-n)+' st'))||'<div class="empty">Inga av dina favoriträtter matchar filtren.</div>';
  $('#more').hidden=true;$('#cards').querySelectorAll('[data-dish]').forEach(b=>b.addEventListener('click',()=>showDish(ds[Number(b.dataset.dish)])));return;}
 const selected=[...inTab(current)];
 const byDeal=(a,b)=>b.deal.level-a.deal.level||b.deal.pct-a.deal.pct||b.deal.save-a.deal.save||a.price-b.price;
 selected.sort(mode==='name'?(a,b)=>a.s.name.localeCompare(b.s.name,'sv')||a.price-b.price:mode==='price'?(a,b)=>a.price-b.price:byDeal);
 const total=mode==='deals'?selected.filter(r=>r.deal.level).length:0,visible=selected.slice(0,limit),offers=visible.slice(0,total),rest=visible.slice(total);
 const section=(title,list,note)=>list.length?`<h2 class="group">${title} <span>${note}</span></h2><div class="grid">${list.map(card).join('')}</div>`:'';
 $('#cards').innerHTML=(section('Bästa erbjudandena',offers,total+' st')+section(total?'Övriga rätter':'Alla rätter',rest,(selected.length-total)+' st'+(mode==='price'?', billigast först':'')))||'<div class="empty">Inga rätter matchar just nu. Prova en högre prisgräns, en annan kategori eller ändra filtren.</div>';
 $('#more').hidden=selected.length<=limit;
 $('#cards').querySelectorAll('[data-index]').forEach(b=>b.addEventListener('click',()=>showHistory(rows[Number(b.dataset.index)])));
}
function showHistory(r){$('#historyTitle').textContent=r.item.name;$('#historyRestaurant').textContent=r.s.name;
 const pts=[...r.stats.points.map(p=>({...p,source:'meny'})),...receiptPoints(receipts,r.s.name,r.item.id,r.item.name)].sort((a,b)=>a.date.localeCompare(b.date));
 const day=d=>new Date(d).toLocaleDateString('sv-SE',{timeZone:'Europe/Stockholm',month:'short',day:'numeric'}),when=p=>p.source==='kvitto'?day(p.date):fmt(p.date);
 if(pts.length<2)$('#chart').innerHTML='<p class="notice">Första priset är sparat. När nästa avläsning är klar visas utvecklingen här.</p>';
 else {const prices=pts.map(p=>p.price),low=Math.min(...prices),high=Math.max(...prices),range=high-low||100,t0=Date.parse(pts[0].date),span=Date.parse(pts.at(-1).date)-t0||1;
  const x=p=>(25+(Date.parse(p.date)-t0)/span*490).toFixed(1),y=p=>(145-(p.price-low)/range*115).toFixed(1);
  const dot=p=>p.source==='kvitto'?`<circle cx="${x(p)}" cy="${y(p)}" r="4.5" fill="#fff" stroke="#ae5b32" stroke-width="2"${p.estimated?' stroke-dasharray="2 2"':''}/>`:`<circle cx="${x(p)}" cy="${y(p)}" r="4" fill="#376849"/>`;
  $('#chart').innerHTML=`<svg viewBox="0 0 540 190" role="img" aria-label="Prisutveckling, från ${esc(money(prices[0]))} till ${esc(money(prices.at(-1)))}"><line x1="25" y1="155" x2="515" y2="155" stroke="#dfe5db"/><polyline points="${pts.map(p=>x(p)+','+y(p)).join(' ')}" fill="none" stroke="#376849" stroke-width="2" stroke-opacity=".45"/>${pts.map(dot).join('')}<text x="25" y="183" font-size="11" fill="#68746d">${esc(when(pts[0]))}</text><text x="515" y="183" text-anchor="end" font-size="11" fill="#68746d">${esc(when(pts.at(-1)))}</text></svg>${pts.some(p=>p.source==='kvitto')?'<p class="legend"><span class="dot menu"></span> Menyavläsning <span class="dot receipt"></span> Eget köp (pris efter rabatt)</p>':''}`;}
 const src=p=>p.source==='kvitto'?(p.estimated?'Eget köp, uppskattat':'Eget köp'):'Menyn';
 $('#historyRows').innerHTML=`<table><thead><tr><th>Datum</th><th>Pris</th><th>Källa</th></tr></thead><tbody>${[...pts].reverse().map(p=>`<tr><td>${esc(when(p))}</td><td>${money(p.price)}</td><td>${src(p)}</td></tr>`).join('')}</tbody></table><p>Jämförelse med ${r.stats.days} tidigare dagar. ${r.stats.days<7?'Minst 7 tidigare dagar krävs för märkningen ”ovanligt lågt”.':''} Egna köp visar vad rätten kostade efter rabatt, utan avgifter och tillval, och räknas inte in i märkningarna.</p>`;$('#historyDialog').showModal();
}
$('#closeDialog').onclick=()=>$('#historyDialog').close();$('#closeDish').onclick=()=>$('#dishDialog').close();$('#more').onclick=()=>{limit+=24;render();};
for(const id of ['search','restaurant','budget','sort','noFish','plus','onlyDeals'])$('#'+id).addEventListener('input',()=>{limit=24;render();});
addEventListener('hashchange',()=>{limit=24;render();scrollTo({top:$('#tabs').offsetTop-8,behavior:'smooth'});});
try{receipts=await fetch('./data/receipts.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null);const response=await fetch('./data/history.json',{cache:'no-store'});if(!response.ok)throw Error('Prisdata kunde inte hämtas');history=normalizeHistory(await response.json());if(!history.readings?.length)throw Error('Ingen avläsning har importerats ännu.');latest=latestSnapshots(history);for(const s of latest)for(const item of s.items){item.stats={true:analyze(item.timeline,item,true,s.observedAt),false:analyze(item.timeline,item,false,s.observedAt)};item.course=course(item);item.bought=purchases(receipts,s.name,item.id,item.name);item.tokens=tokens(item.name);}
 const idf=dishIndex(latest.flatMap(s=>s.items.map(i=>i.name)));groups=dishGroups(receipts?.prices||[],idf).filter(g=>g.times>=2);for(const g of groups){g.members=new Map();for(const s of latest)for(const i of s.items){const k=matchKind(g,idf,s.name,i,i.tokens);if(k)g.members.set(i,k);}}
 const last=history.readings.at(-1).observedAt,dates=new Set(history.readings.map(r=>r.observedAt.slice(0,10)));$('#status').textContent=`${latest.length} restauranger · ${latest.reduce((n,s)=>n+s.items.filter(i=>i.available).length,0)} rätter · uppdaterad ${fmt(last)}`;$('#restaurant').innerHTML+=[...latest].sort((a,b)=>a.name.localeCompare(b.name,'sv')).map(s=>`<option value="${esc(s.url)}">${esc(s.name)}</option>`).join('');
 const age=(Date.now()-Date.parse(last))/3600000;$('#notice').textContent=age>30?`Prislistan är ${Math.floor(age)} timmar gammal. Kontrollera dagens priser hos Wolt.`:dates.size<8?`Prishistoriken har ${dates.size} ${dates.size===1?'dag':'dagar'}. Kampanjer visas redan nu; ”Ovanligt billigt” kräver minst 7 tidigare mätdagar.`:'';$('#notice').hidden=!$('#notice').textContent;render();
}catch(e){$('#notice').textContent=e.message;$('#cards').innerHTML='<div class="empty">Prislistan är inte tillgänglig just nu. Försök igen senare.</div>';}
