import {money,seafood,extra,effectivePrice,analyze} from './lib/prices.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let history=[],latest=[],rows=[],limit=24;const fmt=s=>new Date(s).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
function render(){
 const plus=$('#plus').checked,q=$('#search').value.toLocaleLowerCase('sv'),restaurant=$('#restaurant').value,budget=Number($('#budget').value);
 rows=latest.flatMap(s=>s.items.filter(i=>i.available).map(item=>({s,item,price:effectivePrice(item,plus),stats:analyze(history,{url:s.url,item},plus,s.observedAt)})));
 const seen=new Set();rows=rows.sort((a,b)=>a.item.id.localeCompare(b.item.id)).filter(r=>{const key=JSON.stringify([r.s.url,r.item.name,r.item.description,r.price,r.item.originalPrice,r.item.woltPlus]);if(seen.has(key))return false;seen.add(key);return true;});
 const base=rows.filter(r=>(!$('#noFish').checked||!seafood(r.item))&&($('#extras').checked||!extra(r.item)));
 $('#countHero').textContent=base.filter(r=>r.price<budget).length;
 const selected=base.filter(r=>r.price<budget&&(!restaurant||r.s.url===restaurant)&&(!q||(r.item.name+' '+r.item.description+' '+r.s.name).toLocaleLowerCase('sv').includes(q))&&(!$('#onlyDeals').checked||r.stats.unusual||r.price<r.item.originalPrice));
 const mode=$('#sort').value;selected.sort((a,b)=>mode==='name'?a.s.name.localeCompare(b.s.name,'sv'):mode==='drop'?(a.stats.change??Infinity)-(b.stats.change??Infinity)||a.price-b.price:mode==='price'?a.price-b.price:Number(b.stats.unusual)-Number(a.stats.unusual)||Number(b.price<b.item.originalPrice)-Number(a.price<a.item.originalPrice)||a.price-b.price);
 $('#results').textContent=selected.length+' alternativ';$('#dealCount').textContent=rows.filter(r=>r.price<r.item.originalPrice).length;
 $('#cards').innerHTML=selected.slice(0,limit).map(r=>{const idx=rows.indexOf(r),sale=r.price<r.item.originalPrice,off=Math.round((1-r.price/r.item.originalPrice)*100),st=r.stats;
 const badge=st.unusual?`<span class="badge unusual">${st.discount} % under vanligt</span>`:sale?`<span class="badge">Kampanj −${off} %</span>`:st.lowest?'<span class="badge">Nytt lägsta</span>':'';
 const change=st.change===null?'Första avläsningen':st.change===0?'Oförändrat sedan förra avläsningen':`${st.change<0?'↓':'↑'} ${money(Math.abs(st.change))} sedan förra avläsningen`;
 return `<article class="card"><div class="card-top"><span class="kind">${esc(r.item.category||'Meny')}</span>${badge}</div><h3>${esc(r.item.name)}</h3><div class="venue">${esc(r.s.name)}</div><p class="description">${esc(r.item.description||'Se innehåll och tillval hos restaurangen.')}</p><div class="price-row"><span class="price">${money(r.price)}</span>${sale?`<del>${money(r.item.originalPrice)}</del>`:''}</div>${r.item.woltPlus&&plus?'<div class="membership">Priset kräver Wolt+</div>':''}<div class="change ${st.change<0?'down':''}">${esc(change)}</div><div class="card-bottom"><button class="history-button" data-index="${idx}">↗ Prishistorik</button><a class="order" href="${esc(r.s.url)}" target="_blank" rel="noopener noreferrer">Visa på Wolt ↗</a></div></article>`;}).join('')||'<div class="empty">Inga rätter matchar just nu. Prova en högre prisgräns eller ändra filtren.</div>';
 $('#more').hidden=selected.length<=limit;
 $('#cards').querySelectorAll('[data-index]').forEach(b=>b.addEventListener('click',()=>showHistory(rows[Number(b.dataset.index)])));
}
function showHistory(r){$('#historyTitle').textContent=r.item.name;$('#historyRestaurant').textContent=r.s.name;const pts=r.stats.points;
 if(pts.length<2)$('#chart').innerHTML='<p class="notice">Första priset är sparat. När nästa avläsning är klar visas utvecklingen här.</p>';
 else {const prices=pts.map(p=>p.price),low=Math.min(...prices),high=Math.max(...prices),range=high-low||100;const line=pts.map((p,i)=>`${25+i/(pts.length-1)*490},${145-(p.price-low)/range*115}`).join(' ');$('#chart').innerHTML=`<svg viewBox="0 0 540 190" role="img" aria-label="Prisutveckling, från ${esc(money(prices[0]))} till ${esc(money(prices.at(-1)))}"><line x1="25" y1="155" x2="515" y2="155" stroke="#dfe5db"/><polyline points="${line}" fill="none" stroke="#376849" stroke-width="3"/>${pts.map((p,i)=>`<circle cx="${25+i/(pts.length-1)*490}" cy="${145-(p.price-low)/range*115}" r="4" fill="#376849"/>`).join('')}<text x="25" y="183" font-size="11" fill="#68746d">${esc(fmt(pts[0].date))}</text><text x="515" y="183" text-anchor="end" font-size="11" fill="#68746d">${esc(fmt(pts.at(-1).date))}</text></svg>`;}
 $('#historyRows').innerHTML=`<table><thead><tr><th>Avläst</th><th>Menypris</th></tr></thead><tbody>${[...pts].reverse().map(p=>`<tr><td>${esc(fmt(p.date))}</td><td>${money(p.price)}</td></tr>`).join('')}</tbody></table><p>Jämförelse med ${r.stats.days} tidigare dagar. ${r.stats.days<7?'Minst 7 tidigare dagar krävs för märkningen ”ovanligt lågt”.':''}</p>`;$('#historyDialog').showModal();
}
$('#closeDialog').onclick=()=>$('#historyDialog').close();$('#more').onclick=()=>{limit+=24;render();};
for(const id of ['search','restaurant','budget','sort','noFish','plus','extras','onlyDeals'])$('#'+id).addEventListener('input',()=>{limit=24;render();});
try{const response=await fetch('./data/history.json',{cache:'no-store'});if(!response.ok)throw Error('Prisdata kunde inte hämtas');history=await response.json();if(!history.length)throw Error('Ingen avläsning har importerats ännu.');const map=new Map();for(const s of history)if(!map.has(s.url)||map.get(s.url).observedAt<s.observedAt)map.set(s.url,s);latest=[...map.values()];
 $('#venueCount').textContent=latest.length;$('#itemCount').textContent=latest.reduce((n,s)=>n+s.items.length,0);const last=history.map(s=>s.observedAt).sort().at(-1);$('#updated').textContent=fmt(last);$('#restaurant').innerHTML+=[...latest].sort((a,b)=>a.name.localeCompare(b.name,'sv')).map(s=>`<option value="${esc(s.url)}">${esc(s.name)}</option>`).join('');
 const dates=new Set(history.map(s=>s.observedAt.slice(0,10)));$('#heroNote').textContent=dates.size===1?'Första avläsningen är sparad. Nu börjar prishistoriken.':`${dates.size} dagars prisavläsningar att jämföra med.`;
 const age=(Date.now()-Date.parse(last))/3600000;$('#notice').textContent=age>30?`Prislistan är ${Math.floor(age)} timmar gammal. Kontrollera dagens priser hos Wolt.`:dates.size<8?'Vi bygger prishistoriken. Kampanjer visas redan nu; märkningen ”ovanligt lågt” kommer först när det finns minst 7 tidigare mätdagar.':'Fynd jämförs med tidigare dagspriser. Avläsningar kan missa korta kampanjer.';render();
}catch(e){$('#notice').textContent=e.message;$('#cards').innerHTML='<div class="empty">Prislistan är inte tillgänglig just nu. Försök igen senare.</div>';}
