import {test} from 'node:test';import assert from 'node:assert/strict';import {course,deal,mergeVenues,analyze,effectivePrice,mergeHistory,normalizeHistory,expandVenue,latestSnapshots,itemHistory,seafood,extra} from '../lib/prices.mjs';
import {volumeMl} from '../lib/prices.mjs';
const url='https://wolt.com/sv/swe/stockholm/restaurant/test';const item={id:'a',name:'Pasta',description:'Tomat',category:'Pasta',price:10000,originalPrice:20000,woltPlus:true,offer:'',available:true};
const snap=(day,price=10000)=>({url,name:'Test',observedAt:`2026-09-${day}T12:00:00.000Z`,items:[{...item,price}]});
const timeline=snaps=>itemHistory(snaps.map(s=>s.observedAt),'a',normalizeHistory(snaps).items[url].a);
test('Wolt+ switch compares like-for-like prices',()=>{assert.equal(effectivePrice(item,false),20000);assert.equal(effectivePrice(item,true),10000);});
test('single reading is not a historical deal',()=>{const s=snap('20');const a=analyze(timeline([s]),item,true,s.observedAt);assert.equal(a.unusual,false);assert.equal(a.last,null);assert.equal(a.lowest,false);});
test('20% drop needs seven distinct prior days',()=>{const hist=Array.from({length:7},(_,i)=>snap(String(10+i),15000));const a=analyze(timeline(hist),item,true,'2026-09-20T12:00:00.000Z');assert.equal(a.unusual,true);assert.equal(a.change,-5000);assert.equal(a.median,15000);assert.equal(a.days,7);assert.equal(analyze(timeline(hist.slice(1)),item,true,'2026-09-20T12:00:00.000Z').unusual,false);});
test('repeated checks on one day do not invent seven days of evidence',()=>{const hist=Array.from({length:8},(_,i)=>({...snap('10',15000),observedAt:`2026-09-10T${10+i}:00:00.000Z`}));assert.equal(analyze(timeline(hist),item,true,'2026-09-20T12:00:00.000Z').unusual,false);});
test('old prices outside the window do not determine usual price',()=>{assert.equal(analyze(timeline([snap('01',15000)]),item,true,'2026-10-20T12:00:00.000Z').days,0);});
test('import is idempotent and whitelist removes unrelated fields',()=>{const s={...snap('20'),address:'PRIVATE'};const h=mergeHistory([],{snapshots:[s]});assert.equal(h.readings.length,1);assert.equal(JSON.stringify(h).includes('PRIVATE'),false);assert.equal(mergeHistory(h,{snapshots:[s]}).readings.length,1);});
test('bad prices, foreign links, and empty menus are rejected',()=>{assert.throws(()=>mergeHistory([],{snapshots:[{...snap('20'),url:'https://evil.example/'}]}));assert.throws(()=>mergeHistory([],{snapshots:[snap('20',-1)]}));assert.throws(()=>mergeHistory([],{snapshots:[{...snap('20'),items:[]}]}));});
test('filters detect menu seafood and extras',()=>{assert.equal(seafood({...item,description:'Kyckling med fisksås'}),true);assert.equal(extra({...item,category:'Dryck'}),true);assert.equal(seafood(item),false);});
test('unchanged prices are stored once and every reading can be restored',()=>{const b={...item,id:'b',name:'Pizza'};const days=[{...snap('10'),items:[{...item},b]},{...snap('11'),items:[{...item},b]},{...snap('12',9000),items:[{...item,price:9000}]},{...snap('13',9000),items:[{...item,price:9000},b]}];
 const h=mergeHistory([],{snapshots:days});assert.equal(h.items[url].a.length,2);assert.deepEqual(h.items[url].b.map(e=>e.length),[9,1,9]);
 assert.deepEqual(expandVenue(h,url).map(s=>s.items.map(i=>i.id+i.price)),[['a10000','b10000'],['a10000','b10000'],['a9000'],['a9000','b10000']]);});
test('readings imported out of order are merged correctly',()=>{const h=mergeHistory(mergeHistory([],{snapshots:[snap('12',9000)]}),{snapshots:[snap('10')]});assert.deepEqual(expandVenue(h,url).map(s=>s.items[0].price),[10000,9000]);assert.deepEqual(h.readings.map(r=>r.observedAt.slice(8,10)),['10','12']);});
test('latest menu has stats for the newest reading only',()=>{const h=mergeHistory([],{snapshots:[snap('10',15000),{...snap('11'),items:[{...item,id:'c'}]}]});const [v]=latestSnapshots(h);assert.deepEqual(v.items.map(i=>i.id),['c']);assert.equal(v.observedAt,'2026-09-11T12:00:00.000Z');});
import {receiptPrices,mergeReceipts,receiptPoints,purchases} from '../lib/receipts.mjs';
const rc=(items,discount=0,delivery=0,delivered=true)=>({venue:'Test',date:'2026-09-20',delivered,delivery,discount,items:items.map(([id,price,options=0,count=1])=>({id,name:'Rätt '+id.slice(-1),price,count,options}))});
const ida='a'.repeat(24),idb='b'.repeat(24);
test('receipt discount on one dish is exact when it is a round percentage of that dish',()=>{const [a,b]=receiptPrices(rc([[ida,19600],[idb,4000]],5880));assert.equal(a.price,13720);assert.equal(b.price,4000);assert.equal(a.estimated,false);});
test('receipt discount on the whole order applies the same rate to every dish',()=>{const [a,b]=receiptPrices(rc([[ida,10900],[idb,10100]],8400));assert.equal(a.price,6540);assert.equal(b.price,6060);assert.equal(a.estimated,false);});
test('free delivery inside the discount is not counted as a dish discount',()=>{const [a]=receiptPrices(rc([[ida,18900]],4725+0,4400));assert.equal(a.price,14175);const [b]=receiptPrices(rc([[ida,18000]],1800+3000,3000));assert.equal(b.price,16200);});
test('unclear receipt discounts are spread and marked as estimated; options never raise the dish price',()=>{const [a]=receiptPrices(rc([[ida,20100,800]],7720));assert.equal(a.estimated,true);assert.equal(a.listPrice,20100);assert.ok(a.price<20100);});
test('undelivered orders are skipped and imports are idempotent',()=>{assert.deepEqual(receiptPrices(rc([[ida,10000]],0,0,false)),[]);const batch={receipts:[rc([[ida,10000]])]};const s=mergeReceipts(null,batch);assert.equal(mergeReceipts(s,batch).prices.length,1);assert.equal(receiptPoints(s,'Test',ida)[0].price,10000);});
test('receipts without valid ids or dates are rejected',()=>{assert.throws(()=>mergeReceipts(null,{receipts:[{...rc([[ida,1]]),date:'igår'}]}));assert.throws(()=>mergeReceipts(null,{receipts:[rc([['x',1]])]}));});
test('venues without a link are kept until a reading with the same name links them',()=>{const h=mergeHistory([],{snapshots:[{...snap('10'),name:'El Birria Express'}]});const v=mergeVenues([{name:'Test2',url:url+'2'},{name:'el birria express'},{name:'Muskot'}],h);assert.deepEqual(v,[{name:'Test2',url:url+'2'},{name:'El Birria Express',url},{name:'Muskot'}]);assert.deepEqual(mergeVenues([],h),[{name:'El Birria Express',url}]);});
test('menu categories are sorted into tabs',()=>{const c=(category,name='Rätt')=>course({...item,category,name});assert.equal(c('Pizza'),'mat');assert.equal(c('KALLA DRYCKER ❄️🥤'),'dryck');assert.equal(c('Kampanj','Coca-Cola 33 cl'),'dryck');assert.equal(c('Frukosterbjudande'),'frukost');assert.equal(c('Kondisbitar & Bakelser'),'fika');assert.equal(c('TILLBEHÖR & DIP'),'smatt');assert.equal(c('Bröd','Garlic Naan'),'smatt');assert.equal(c('FLAME-GRILLED SINGEL 🍔','Extra Long Chili Cheese'),'mat');assert.equal(c('Barnrätter'),'barn');assert.equal(c('Kebabrätter','Kebabtallrik med vitlökssås'),'mat');
 assert.equal(c('Varma Mackor','Kyckling Avo'),'frukost');assert.equal(c('Sandwiches','The Steak'),'frukost');assert.equal(c('Kampanj','Räksmörgås'),'frukost');assert.equal(c('Bundles','Juice & Sandwich Combo x 2'),'frukost');
 assert.equal(c('KYCKLING','Grand Chicken Sandwich-mål'),'mat');assert.equal(c('Oxfilé-& Fläskfilépizzor','Gudfadern'),'mat');assert.equal(c('Combo Deals','Huli huli burrito + ramlösa'),'mat');assert.equal(c('Kampanj','Margherita inkl. dryck'),'mat');
 assert.equal(c('Kampanj','Ramlösa Citrus'),'dryck');assert.equal(c('Populärt','Iced Latte 16oz'),'dryck');assert.equal(c('Bundles','Acai Breakfast Combo Offer'),'frukost');assert.equal(c('Barnmeny','Pannkakor'),'barn');
 assert.equal(c('Kebabrätter','Bröd'),'smatt');assert.equal(c('Nachos','Dip Selection'),'smatt');assert.equal(c('Kampanj','Tiramisu'),'fika');assert.equal(c('Dessert','Nutella pizza'),'fika');assert.equal(c('Pizza','Nutella'),'mat');
 const p=(category,name,kr)=>course({...item,category,name,price:kr*100,originalPrice:kr*100});
 assert.equal(p('Bestick','Bestick',0),null);assert.equal(p('MINIMÅL','Minimål med Chicken Jr',74),'barn');assert.equal(p('Snacks','Barnmeny Nuggets',69),'barn');
 assert.equal(p('Sås','Vitlökssås 10 cl',25),'smatt');assert.equal(p('Yama Home','Nama Soy Sauce 200ml',89),'smatt');assert.equal(p('Glass',"Glass Half Baked 465ml - Ben & Jerry's",99),'fika');
 assert.equal(p('MAX CLASSICS',"Classic '68 Cheese",111),'mat');assert.equal(p('Frapino','Choklad Frapino Standard',80),'dryck');assert.equal(p('Eftrerrätter','Äppelpaj',55),'fika');
 assert.equal(p('Dipp','Chili Majo',10),'smatt');assert.equal(p('Något Extra','Guacamole',27),'smatt');assert.equal(p('Tillbehör','Dipped Churros',59),'fika');
 assert.equal(p('Smashburgare','Chiliburgare + pommes',104),'mat');assert.equal(p('Hamburgare','Smash burgare 200g Cheese inkl pommes',230),'mat');assert.equal(p('Smashburgare Meny (Dryck och pommes ingår)','Smash Original - Meny',169),'mat');
 assert.equal(p('Tilltugg','Pannoumi Fries',87),'smatt');
 assert.equal(p('Yama Kids','Beginners Chopsticks',39),null);assert.equal(p('Extra & vegetariska','Beyti',199),'mat');assert.equal(p('Amerikanska Pan Pizzor','Late Breakfast',159),'mat');
 assert.equal(p('Yama Home','Cooked Sushi Rice 500g',49),'smatt');assert.equal(p('Kall Mat','Grekisk Yoghurt med Jordgubbar',49),'frukost');assert.equal(p("Winnin' Deals",'FikaDeal',35),'fika');
 assert.equal(p('Övriga Rätter','Ost & Kalkontoast',36),'frukost');assert.equal(p('KYCKLING','Grilled Chicken Sandwich',89),'mat');assert.equal(p('Sharing is Caring','TB Holy Habanerosås',70),'smatt');
 assert.equal(p('Kampanj','Tre Sideorders för 99kr',99),'smatt');assert.equal(p('Kampanj','Köttbullar i gräddsås',79),'mat');assert.equal(p('Korv','Premium Korv med Stor Baguette',100),'mat');assert.equal(p('DESSERT','Chocolate Dip',15),'smatt');assert.equal(p('Desserter','Äppelpaj',15),'fika');assert.equal(p('CHICKEN TENDERS','Hot Habanero-krydda',8),'smatt');assert.equal(p('CHICKEN TENDERS',"XL Raising MAX's Sauce",38),'smatt');assert.equal(p('Kampanj','Biff i pepparsås',189),'mat');});
test('offers are ranked: unusually cheap, then campaign, then new lowest',()=>{const s={unusual:false,discount:null,median:null,lowest:false,change:null,last:null};
 assert.deepEqual(deal(item,10000,{...s,unusual:true,discount:33,median:15000}),{level:3,label:'Ovanligt billigt',pct:33,save:5000});
 assert.equal(deal(item,10000,s).level,2);assert.equal(deal(item,10000,s).pct,50);
 const full={...item,price:20000};assert.equal(deal(full,20000,{...s,lowest:true,last:21000}).level,1);assert.equal(deal(full,20000,{...s,change:-500}).label,'Sänkt pris');assert.equal(deal(full,20000,s).level,0);
 const tiny={...item,price:400,originalPrice:800};assert.equal(deal(tiny,400,s).level,0);assert.equal(deal(tiny,400,{...s,unusual:true,discount:50,median:800}).level,0);
 assert.equal(deal(item,19900,s).level,0);assert.equal(deal(full,20000,{...s,change:-100}).level,0);assert.equal(deal(full,20000,{...s,lowest:true,last:20100}).level,0);});
test('own purchases count order days and the usual price, also when Wolt changed the dish ID',()=>{const store={prices:[{venue:'V',date:'2026-09-01',id:'old',name:'Tikka Masala',price:14000},{venue:'V',date:'2026-09-10',id:'new',name:'Tikka Masala',price:12000},{venue:'V',date:'2026-09-10',id:'new',name:'Tikka Masala',price:12000},{venue:'V',date:'2026-09-20',id:'new',name:'Tikka Masala',price:13000},{venue:'Annan',date:'2026-09-20',id:'new',name:'Tikka Masala',price:1}]};
 assert.deepEqual(purchases(store,'V','new','tikka masala'),{times:3,usual:12500,last:{date:'2026-09-20',price:13000}});
 assert.equal(purchases(store,'V','x','Pizza'),null);assert.equal(receiptPoints(store,'V','new','Tikka Masala').length,4);assert.equal(receiptPoints(store,'V','new').length,3);});
import {tokens,dishIndex,dishGroups,inGroup,matchKind,similarity,THRESHOLD} from '../lib/dishes.mjs';
const menuNames=['Chicken Tikka Butter Masala','Lamm Tikka Butter Masala','Paneer Butter Masala','Chicken Sambal Masala','Naan','Garlic Naan','Margherita','Pizza Margherita','Lasagne al Forno','Halloumi Sticks','Mozzarella Sticks','Nacho De Luxe','Kyckling Tikka Masala'];
const idf=dishIndex(menuNames),sim=(a,b)=>similarity(idf,tokens(a),tokens(b));
test('similar dishes match across restaurants but not across proteins',()=>{
 assert.ok(sim('Tikka Masala Chicken','Chicken Tikka Butter Masala')>=THRESHOLD);assert.ok(sim('Chicken Tikka Butter Masala','Kyckling Tikka Masala')>=THRESHOLD);
 assert.equal(sim('Chicken Tikka Butter Masala','Lamm Tikka Butter Masala'),0);assert.equal(sim('Chicken Tikka Butter Masala','Paneer Butter Masala'),0);
 assert.ok(sim('Margherita inkl. dryck','Pizza Margherita')>=THRESHOLD);assert.ok(sim('Lasagne Al Forno','Lasagne al Forno')>=THRESHOLD);assert.ok(sim('Nacho De Luxe Super Grande','Nacho De Luxe')>=THRESHOLD);
 assert.ok(sim('Halloumi Sticks','Mozzarella Sticks')<THRESHOLD);assert.ok(sim('Naan','Garlic Naan')<THRESHOLD);});
test('purchases of the same dish at different restaurants form one group',()=>{const p=(venue,date,id,name,price)=>({venue,date,id,name,price});
 const gs=dishGroups([p('Ellora','2026-09-01','a','Chicken Tikka Butter Masala',14000),p('Ellora','2026-09-05','a','Chicken Tikka Butter Masala',14000),p('Muskot','2026-09-07','m','Tikka Masala Chicken',12000),p('Ellora','2026-09-07','n','Naan',4000)],idf);
 assert.equal(gs.length,2);assert.deepEqual([gs[0].title,gs[0].times,gs[0].usual,gs[0].venues],['Chicken Tikka Butter Masala',3,14000,['Ellora','Muskot']]);
 const g=gs[0],item=(id,name)=>({id,name});assert.ok(inGroup(g,idf,'Annan','x'&&item('x','Kyckling Tikka Masala'),tokens('Kyckling Tikka Masala')));assert.ok(!inGroup(g,idf,'Ellora',item('l','Lamm Tikka Butter Masala'),tokens('Lamm Tikka Butter Masala')));assert.ok(inGroup(g,idf,'Muskot',item('m','Helt annat namn'),tokens('Helt annat namn')));});
test('a smaller variant of a bought dish is marked as variant, not compared with the usual price',()=>{const g=dishGroups([{venue:'T',date:'2026-09-01',id:'n',name:'Nacho De Luxe Super Grande',price:17500}],idf)[0],kind=n=>matchKind(g,idf,'T',{id:'x',name:n},tokens(n));assert.equal(kind('Nacho De Luxe'),'variant');assert.equal(kind('nacho de luxe super grande'),'exact');assert.equal(kind('Margherita'),null);});
import {cleanImage,mergeImages,imageFor,validateBatch} from '../lib/prices.mjs';
const img='https://imageproxy.wolt.com/menu/menu-images/shared/abc_pizza.jpg';
test('image links are kept only for Wolt image server over https, without size parameters',()=>{assert.equal(cleanImage(img+'?w=600'),img);assert.equal(cleanImage(''),'');for(const bad of ['http://imageproxy.wolt.com/x.jpg','https://evil.example/x.jpg','https://imageproxy.wolt.com.evil.example/x.jpg','javascript:alert(1)','https://user@imageproxy.wolt.com/x.jpg'])assert.throws(()=>cleanImage(bad));
 const [s]=validateBatch({snapshots:[{...snap('20'),items:[{...item,image:img+'?w=200'}]}]});assert.equal(s.items[0].image,img);assert.throws(()=>validateBatch({snapshots:[{...snap('20'),items:[{...item,image:'https://evil.example/a.jpg'}]}]}));});
test('a new image link is not a change in the price log',()=>{const a={...snap('10'),items:[{...item,image:img}]},b={...snap('11'),items:[{...item,image:img.replace('abc','def')}]};const h=mergeHistory([],{snapshots:[a,b]});assert.equal(h.items[url].a.length,1);assert.equal(JSON.stringify(h).includes('imageproxy'),false);});
test('image store keeps the latest image per restaurant and dish, also for out-of-order imports',()=>{const newer={...snap('12'),items:[{...item,image:img.replace('abc','new')}]},older={...snap('10'),items:[{...item,image:img}]};
 let st=mergeImages(null,validateBatch({snapshots:[newer]}));st=mergeImages(st,validateBatch({snapshots:[older]}));assert.equal(imageFor(st,url,'a'),img.replace('abc','new'));
 st=mergeImages(st,validateBatch({snapshots:[{...snap('13'),items:[{...item,image:''}]}]}));assert.equal(imageFor(st,url,'a'),img.replace('abc','new'));assert.equal(imageFor(st,url,'saknas'),'');});
import {feeModel,withFees} from '../lib/fees.mjs';
test('fees are estimated from own receipts as a share of the ordinary price',()=>{const o=(venue,date,list,fees)=>({venue,date,list,fees});
 const m=feeModel({orders:[o('A','2026-07-01',20000,1000),o('A','2026-09-01',20000,1600),o('B','2026-09-02',10000,800),o('C','2026-09-03',18900,10345)]});
 assert.equal(m.venues.has('C'),false);assert.equal(m.venues.get('A').n,2);
 assert.deepEqual(withFees(m,'B',7000,10000),{fee:800,total:7800,ratio:0.08,orders:1});
 assert.equal(withFees(m,'Ny restaurang',10000,10000).fee,Math.round(10000*m.all));assert.equal(withFees(null,'B',1,1),null);assert.equal(feeModel({orders:[]}),null);});
import {validateFoodora,mergeFoodora,foodoraMenu,matchFoodora,foodoraPrice,foodoraPoints} from '../lib/foodora.mjs';
const fdUrl='https://www.foodora.se/restaurant/ab12/test-restaurang',fdItem={id:'pasta',name:'Pasta',category:'Pasta',price:9500,originalPrice:9500,proPrice:null,from:true};
const fsnap=(day,items=[fdItem])=>({url:fdUrl,wolt:url,name:'Test',observedAt:`2026-09-${day}T12:00:00.000Z`,items});
test('Foodora links and prices are validated',()=>{assert.equal(validateFoodora({foodora:[fsnap('20')]})[0].url,fdUrl);
 for(const bad of [{url:'https://evil.example/restaurant/a/b'},{wolt:'https://evil.example/x'},{items:[{...fdItem,price:-1}]},{items:[{...fdItem,proPrice:20000}]},{items:[]}])assert.throws(()=>validateFoodora({foodora:[{...fsnap('20'),...bad}]}));});
test('Foodora log only grows when a price changes and keeps the latest menu',()=>{let st=mergeFoodora(null,{foodora:[fsnap('10'),fsnap('11'),fsnap('12',[{...fdItem,price:8900,originalPrice:9500}])]});
 assert.equal(st.venues[url].items.pasta.log.length,2);const m=foodoraMenu(st,url);assert.equal(m.items[0].price,8900);assert.equal(m.items[0].from,true);
 st=mergeFoodora(st,{foodora:[fsnap('09',[{...fdItem,price:1}])]});assert.equal(foodoraMenu(st,url).items[0].price,8900);
 st=mergeFoodora(st,{foodora:[fsnap('13',[{...fdItem,id:'pizza',name:'Pizza'}])]});assert.deepEqual(foodoraMenu(st,url).items.map(i=>i.id),['pizza']);
 assert.deepEqual(foodoraPoints(foodoraMenu(mergeFoodora(null,{foodora:[fsnap('10')]}),url).items[0],false).map(p=>p.price),[9500]);});
test('dishes are matched to Foodora only on the same name; duplicates need the same category or price',()=>{
 const st=mergeFoodora(null,{foodora:[fsnap('10',[{...fdItem,id:'a',name:'Chicken Tikka Butter Masala'},{...fdItem,id:'b',name:'Naan',category:'Bröd',price:3200,originalPrice:3200},{...fdItem,id:'c',name:'Naan',category:'Tillbehör',price:3500,originalPrice:3500},{...fdItem,id:'d',name:'Lassi',price:3000,originalPrice:3500,proPrice:2500}])]}),m=foodoraMenu(st,url);
 assert.equal(matchFoodora(m,{name:'chicken tikka butter-masala'}).id,'a');assert.equal(matchFoodora(m,{name:'Chicken Tikka'}),null);
 assert.equal(matchFoodora(m,{name:'Naan',category:'Bröd'}).id,'b');assert.equal(matchFoodora(m,{name:'Naan',category:'Övrigt'}),null);
 const l=matchFoodora(m,{name:'Lassi'});assert.equal(foodoraPrice(l,false),3000);assert.equal(foodoraPrice(l,true),2500);assert.equal(matchFoodora(null,{name:'x'}),null);});
test('drink volume is read from the name',()=>{
 const v=volumeMl;assert.equal(v('Coca-Cola 33 cl'),330);assert.equal(v('Pepsi Max 1,5L'),1500);assert.equal(v('Ramlösa 50cl'),500);assert.equal(v('Iced Latte 16oz'),473);
 assert.equal(v('Fruktdryck Apelsin 250 ml - Smakis'),250);assert.equal(v('Coca-Cola 6 x 33 cl'),1980);assert.equal(v('4-pack - Burk läsk'),null);assert.equal(v('Fanta'),null);assert.equal(v('Vatten 0,33 l'),330);});
test('quick filters: name decides, menu category only for cuisines',async()=>{
 const {subcatsFor}=await import('../lib/subcats.mjs');const f=(name,category,c='mat')=>subcatsFor({name,category},c);
 assert.deepEqual(f('Chicken Tikka Butter Masala','Kampanj!'),['indiskt','kyckling']);assert.ok(f('Picasso','Pizzor').includes('pizza'));
 assert.deepEqual(f('Filét-o-Fish®','Kyckling, Fisk & Vego'),['fisk']);assert.ok(!f('Double Gourmet Grill Bacon & Cheese Meal','GOURMET MENYER').includes('grill'));
 assert.deepEqual(f('Coca-Cola 33 cl','Dryck','dryck'),['lask']);assert.deepEqual(f('Ramlösa Citrus 33cl','Dryck','dryck'),['vatten']);
 assert.deepEqual(f('Lökringar','TILLBEHÖR & DIP','smatt'),['ost']);assert.deepEqual(f('Vitlökssås 10 cl','Sås','smatt'),['saser']);assert.deepEqual(f('Pizza','x','mina'),[]);
 assert.ok(!f('Röd Curry','Thairätter').includes('indiskt'));assert.ok(!f('Dal mare','Pasta').includes('indiskt'));assert.ok(!f('Grilled Chicken Parmesan','KYCKLING').includes('grill'));
 assert.ok(!f('Veggie Strips Meal','Veggie').includes('kyckling'));assert.ok(!f('Scampitallrik','Tallrikar').includes('kebab'));assert.ok(!f('Bolognese','Italienska Pizzor').includes('pasta'));
 assert.deepEqual(f('Classico Bryggkaffe','Varm dryck','dryck'),['kaffe']);assert.deepEqual(f('Vattenmelonslemonad','Kall dryck','dryck'),['juice']);assert.deepEqual(f('Capri-Sun Monster 200 ml','Dryck','dryck'),[]);
 assert.deepEqual(f('Garlic Dip','Dips','smatt'),['saser']);assert.deepEqual(f('Fries & Dip','Sides','smatt'),['pommes']);assert.deepEqual(f('Äppelklyftor','Tillbehör','smatt'),[]);
 assert.deepEqual(f("Ben & Jerry's Cookie Dough 465 ml",'Glass','fika'),['glass']);assert.deepEqual(f('Morotskaka','Bakverk','fika'),['kakor']);});
